name: catcher
description: Plugin for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 0.6.6
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/catcher

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.0.6
  device_info_plus: ^2.0.1
  device_info_plus_platform_interface: ^2.0.0
  package_info_plus: ^1.0.1
  mailer: ^5.0.0
  dio: ^4.0.0
  flutter_mailer: ^2.0.0-null-safe
  logging: ^1.0.1
  sentry: ^5.0.0
  universal_io: ^2.0.4

dev_dependencies:
  lint: ^1.5.3

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.catcher
        pluginClass: CatcherPlugin
      ios:
        pluginClass: CatcherPlugin
      web:
        pluginClass: CatcherWebPlugin
        fileName: catcher_web_plugin.dart
      macos:
        pluginClass: CatcherPlugin
      windows:
        pluginClass: CatcherPlugin
      linux:
        pluginClass: CatcherPlugin
