name: catcher
description: Plugin for error catching. Allows handling errors when they're not catched by developer. Plugin provides multiple handlers for errors.
version: 0.3.12
author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/catcher

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
     sdk: flutter
  fluttertoast: ^4.0.1
  device_info: ^0.4.2+1
  package_info: '>=0.4.0+16 <2.0.0'
  mailer: ^3.0.4
  dio: ^3.0.9
  flutter_mailer: ^0.5.0
  logging: ^0.11.4
  sentry: ^3.0.0+1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: CatcherWeb
        fileName: core/catcher_web.dart
      android:
        package: com.jhomlala.catcher
        pluginClass: CatcherPlugin
      ios:
        pluginClass: CatcherPlugin
