name: catcher
description: Plugin for error catching which provides multiple handlers for dealing with errors when they are not caught by the developer.
version: 1.0.0-dev1
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/catcher
repository: https://github.com/jhomlala/catcher
issue_tracker: https://github.com/jhomlala/catcher/issues
topics:
  - error
  - errors
  - logs
  - devtools
  - tool

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fluttertoast: ^8.2.6
  device_info_plus: ^10.1.0
  device_info_plus_platform_interface: ^7.0.0
  package_info_plus: ^8.0.0
  mailer: ^6.1.0
  dio: ^5.4.3+1
  flutter_mailer: ^2.1.2
  logging: ^1.2.0
  sentry: ^8.2.0
  universal_io: ^2.2.2

dev_dependencies:
  very_good_analysis: ^5.1.0
